apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    pv: postgres-pv
spec:
  capacity:
    storage: {{ .Values.db.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd
  hostPath:
    path: /mnt/postgres
