apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    pv: redis-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd
  hostPath:
    path: /mnt/redis

