{{- if .Values.isDev}}
apiVersion: v1
kind: Service
metadata:
  name: api-np
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
{{- end}}