{{- if .Values.isDev}}

apiVersion: v1
kind: Service
metadata:
  name: postgres-np
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres

{{- end}}
