apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /data
              name: redis-storage              
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc